'use client'

import { useState } from 'react'
import Link from 'next/link'

export default function Home() {
    const [hoveredCard, setHoveredCard] = useState(null)

    const features = [
        {
            id: 1,
            title: 'AI-Powered Learning',
            description: 'Personalized learning paths generated by advanced AI to match your pace and style',
            icon: '🤖',
            gradient: 'from-blue-500 to-cyan-500'
        },
        {
            id: 2,
            title: 'Bite-Sized Content',
            description: 'Learn in 5-minute chunks that fit perfectly into your busy schedule',
            icon: '⚡',
            gradient: 'from-purple-500 to-pink-500'
        },
        {
            id: 3,
            title: 'Track Progress',
            description: 'Visual analytics and insights to monitor your learning journey',
            icon: '📊',
            gradient: 'from-orange-500 to-red-500'
        },
        {
            id: 4,
            title: 'Interactive Quizzes',
            description: 'Reinforce learning with engaging quizzes and instant feedback',
            icon: '🎯',
            gradient: 'from-green-500 to-emerald-500'
        }
    ]

    return (
        <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
            {/* Animated Background */}
            <div className="absolute inset-0 overflow-hidden">
                <div className="absolute -top-40 -right-40 w-80 h-80 bg-purple-500 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-pulse-slow"></div>
                <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-cyan-500 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-pulse-slow animation-delay-2000"></div>
                <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-80 h-80 bg-pink-500 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-pulse-slow animation-delay-4000"></div>
            </div>

            {/* Navigation */}
            <nav className="relative z-10 px-6 py-6">
                <div className="max-w-7xl mx-auto flex justify-between items-center">
                    <div className="flex items-center space-x-2">
                        <span className="text-3xl">📚</span>
                        <h1 className="text-2xl font-bold text-white">MicroLearn</h1>
                    </div>
                    <div className="flex gap-4">
                        <button className="btn-secondary"><Link href="/sign-in">Sign In</Link></button>
                        <button className="btn-primary"><Link href="/sign-up">Get Started</Link></button>
                    </div>
                </div>
            </nav>

            {/* Hero Section */}
            <main className="relative z-10 px-6 pt-20 pb-32">
                <div className="max-w-7xl mx-auto">
                    {/* Hero Content */}
                    <div className="text-center mb-20 animate-fade-in">
                        <h2 className="text-6xl md:text-7xl font-bold text-white mb-6 leading-tight">
                            Learn Smarter,
                            <br />
                            <span className="bg-gradient-to-r from-cyan-400 via-purple-400 to-pink-400 text-transparent bg-clip-text">
                                Not Harder
                            </span>
                        </h2>
                        <p className="text-xl text-gray-300 mb-8 max-w-2xl mx-auto">
                            Master new skills with AI-powered micro-lessons designed for your busy life.
                            Just 5 minutes a day to unlock your potential.
                        </p>
                        <div className="flex gap-4 justify-center">
                            <button className="btn-primary text-lg px-8 py-4">
                                Start Learning Free
                            </button>
                            <button className="btn-secondary text-lg px-8 py-4">
                                Watch Demo
                            </button>
                        </div>
                    </div>

                    {/* Stats Section */}
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-20">
                        {[
                            { number: '10K+', label: 'Active Learners' },
                            { number: '500+', label: 'Micro Lessons' },
                            { number: '95%', label: 'Success Rate' }
                        ].map((stat, index) => (
                            <div
                                key={index}
                                className="card-glass text-center transform hover:scale-105 transition-transform duration-300 animate-slide-up"
                                style={{ animationDelay: `${index * 100}ms` }}
                            >
                                <div className="text-4xl font-bold bg-gradient-to-r from-cyan-400 to-purple-400 text-transparent bg-clip-text mb-2">
                                    {stat.number}
                                </div>
                                <div className="text-gray-300">{stat.label}</div>
                            </div>
                        ))}
                    </div>

                    {/* Features Grid */}
                    <div className="mb-20">
                        <h3 className="text-4xl font-bold text-white text-center mb-12">
                            Why Choose MicroLearn?
                        </h3>
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                            {features.map((feature, index) => (
                                <div
                                    key={feature.id}
                                    className="card-glass group cursor-pointer transform transition-all duration-300 hover:scale-105"
                                    onMouseEnter={() => setHoveredCard(feature.id)}
                                    onMouseLeave={() => setHoveredCard(null)}
                                    style={{ animationDelay: `${index * 100}ms` }}
                                >
                                    <div className={`text-5xl mb-4 transform transition-transform duration-300 ${hoveredCard === feature.id ? 'scale-110 rotate-12' : ''
                                        }`}>
                                        {feature.icon}
                                    </div>
                                    <h4 className="text-xl font-semibold text-white mb-3">
                                        {feature.title}
                                    </h4>
                                    <p className="text-gray-300 text-sm leading-relaxed">
                                        {feature.description}
                                    </p>
                                    <div className={`mt-4 h-1 rounded-full bg-gradient-to-r ${feature.gradient} transform origin-left transition-transform duration-300 ${hoveredCard === feature.id ? 'scale-x-100' : 'scale-x-0'
                                        }`}></div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* CTA Section */}
                    <div className="card-glass text-center py-16 px-8">
                        <h3 className="text-4xl font-bold text-white mb-4">
                            Ready to Transform Your Learning?
                        </h3>
                        <p className="text-xl text-gray-300 mb-8 max-w-2xl mx-auto">
                            Join thousands of learners who are achieving their goals with just 5 minutes a day
                        </p>
                        <button className="btn-primary text-lg px-10 py-4">
                            Get Started Now - It's Free
                        </button>
                    </div>
                </div>
            </main>

            {/* Footer */}
            <footer className="relative z-10 border-t border-white/10 py-8">
                <div className="max-w-7xl mx-auto px-6 text-center text-gray-400">
                    <p>&copy; 2025 MicroLearn. Empowering learners worldwide.</p>
                </div>
            </footer>
        </div>
    )
}
